package com.clientname.androidbase.enums;



public enum EScreenType {

    LOGIN_SCREEN, SIGN_UP_SCREEN, SONG_LIST_SCREEN, PLAYLIST_SCREEN, MEDIA_LIST_SCREEN, MEDIA_PLAY_SCREEN, VIDEO_LIST_SCREEN, PLAY_LIST_SONG_SCREEN, CREATE_PLAN_SCREEN, TODO_LIST_SCREEN, FRIENDS_EXPENSES, GROUP_EXPENSES, HISTORY_EXPENSES, RECENT_CONTACT_LIST, CONTACT_LIST, PROFILE_SCREEN, PROFILE_SETTINGS, CONTACT_INFO, CHANGE_PASSWORD, SONG_FOLDER_SCREEN, FOLDER_PATH_SONGS, CREATE_FOOT_PRINT_SCREEN
}
